name: Zeyple test and deb package build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 2.7
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install debconf-utils
          sudo debconf-set-selections <<< "postfix postfix/main_mailer_type string 'Local only'"
          sudo debconf-set-selections <<< "postfix postfix/mailname string localhost"
          sudo apt-get install -y mailutils ruby ruby-dev rubygems build-essential sudo gnupg python-gpg libgpgme-dev swig
          python -m pip install --upgrade pip
          pip install -r requirements_gpg.txt
          sudo gem install --no-ri --no-rdoc fpm
      - name: Test
        run: python -m pytest tests/
      - name: Build deb package
        run: ./fpm/create
      - name: End to end test using deb package
        run:  sudo bash -ex ./tests/e2e.sh 
      - name: Upload deb package
        uses: actions/upload-artifact@v1
        with:
          name: zeyple.deb
          path: ./fpm/zeyple.deb
